version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount for development (comment out for production)
      - .:/usr/share/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - erotica-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erotica.rule=Host(`localhost`)"
      - "traefik.http.routers.erotica.entrypoints=web"
      - "traefik.http.services.erotica.loadbalancer.server.port=80"

networks:
  erotica-network:
    driver: bridge

# Optional: Add reverse proxy for production
# services:
#   traefik:
#     image: traefik:v2.10
#     command:
#       - "--api.insecure=true"
#       - "--providers.docker=true"
#       - "--providers.docker.exposedbydefault=false"
#       - "--entrypoints.web.address=:80"
#       - "--entrypoints.websecure.address=:443"
#     ports:
#       - "80:80"
#       - "443:443"
#       - "8080:8080"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#     networks:
#       - erotica-network
